GodotVR/godot_openxr

SConstruct
src/OS.cpp
src/OS.h
src/OpenXRApi.cpp
src/OpenXRApi.h

Invalid pose means that the view pose quaternion may not be a valid (normalized) quaternion, which means xrEndFrame() will fail when supplied our projection layer with this view pose.

Skip render when xrLocateViews returns invalid pose

---

src/OpenXRApi.cpp

On Linux the `get_native_handle()` function in the godot_openxr plugin failed completely and my debugger linked my only to the prototype in godot's OS class https://github.com/godotengine/godot/blob/150f9ce807e7b9be45bf8c030faa80510aea8407/core/os/os.h#L255. No idea what went wrong there but renaming the class in godot_openxr fixed it d7c04f7.

use get_native_handle() for xlib on linux 

---

src/OpenXRApi.cpp
src/OpenXRApi.h

Make the MeshInstances on the HandControllers visible in the editor to see blocks for hands.
fixes #26
This PR is not actually tested on a runtime without hand tracking ext support.

only enable hand tracking ext if supported

---

SConstruct

Clang 6.0:
clang -o glad/glad.os -c -fPIC -O3 -std=c++17 -fPIC -Iglad -I. -Isrc -Igodot-cpp/godot_headers -Igodot-cpp/include -Igodot-cpp/include/core -Igodot-cpp/include/gen -Iopenxr_loader_windows/1.0.12/include glad/glad.c
error: invalid argument '-std=c++17' not allowed with 'C'

scons: Don't set std=c++17 for CCFLAGS

---

demo/addons/godot-openxr/editor/OpenXRRunSelect.gd
demo/addons/godot-openxr/editor/OpenXRRunSelect.tscn
demo/addons/godot-openxr/plugin.cfg
demo/addons/godot-openxr/plugin.gd
demo/addons/godot-openxr/runtimes.json
demo/project.godot

Adding a dropdown (windows only) to the editor that allows us to select from different (known) runtimes:
The known runtimes are stored in `runtimes.json` in our addons folder so we can easily add more entries. On reading the JSON we will check if the paths to the runtime files exist and only offer those we find. We'll probably need to make it smarter to check the same path on different drives in case the user has decided to install Oculus/Steam on a D: or E: drive or something but that is for an enhancement PR.
If the current runtime is not found in the list, it is added (in editor only, the `runtimes.json` is not altered).

Adding a runtime selection dropdown into the editor

---

README.md

Probably not many people need to use a 3.2.4 beta and miss the info that it can work on those too.

update godot requirement to 3.3 in readme

---

.github/workflows/build-on-push.yml
README.md
SConstruct
src/ARVRInterface.cpp

Updates Godot-cpp to 3.3, we no longer need a beta copy of the api.json. 
Note that due to folder and sub-module changes it's easier to just clone a new folder

Updating godot-cpp to 3.3

---

CONTRIBUTORS.md
LICENSE

We still have the original contributors file from the OpenHMD plugin. I don't think the current plugin has much in common with that anymore :) 
Updated it to reflect who have been contributing here.
That said, Christoph let me know if I should leave some of the names in there if they contributed to the original plugin before we moved it here.

Updated contributors, it was still the original one from OpenHMD

---

demo/addons/godot-openxr/CHANGES.md
src/openxr/OpenXRApi.cpp
src/openxr/OpenXRApi.h

Finally got around to testing OpenXR with Oculus Link and indeed got things to crash when you take off the headset and put it back on.
Oculus Link gets an `XR_SESSION_STATE_FOCUSED` every time you put the headset back on and we were initializing the action set at this point in time. As it already was initialized the second initialization failed.
I'm keeping a status now to prevent double init. There is probably more to this in the future if we ever have a reason for re-initializing the action set but that's for another day.

Fix re-init of action sets when headset refocusses

---

SConstruct
demo/Main.tscn
demo/addons/godot-openxr/CHANGES.md
demo/project.godot
src/openxr/OpenXRApi.cpp
src/openxr/OpenXRApi.h
src/openxr/OpenXRHand.cpp
src/openxr/OpenXRHand.h
src/openxr/OpenXRSkeleton.cpp
src/openxr/OpenXRSkeleton.h

This implements the motion range extension provided this is supported by the OpenXR runtime.
This allows you to toggle the range for finger tracking:
- Unobstructed will make a closed first when the user grabs the controller (default)
- Conform to controller will limit the range of the fingers so it grabs the controller 
These are the only two models currently supported by OpenXR but more will likely be added in the future. 
You can switch between the modes at runtime, so you could use unobstructed and not show the controller, then when something is picked up you can go back to the conform to controller mode. 
Note that there is only one setting tracked per hand so if you use multiple Hand/Skeleton nodes for each hand the last one wins. It's assumed you don't represent a hand more then …

Add motion range support

---

src/openxr/OpenXRApi.cpp
src/openxr/OpenXRApi.h
src/openxr/actions/action.cpp

Just a quick and dirty first pass so far but working on moving parts of the initialisation of the plugin to the proper timing as far as the OpenXR lifecycle is concerned.
Right now we do almost all initialisation right away but according to the documentation:
https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#session
We're supposed to wait on state changes once the session is created before proceeding. 
This should also enable us to react properly on the OpenXR runtime requesting a session to be ended and on quitting the application.

Reworking lifecycle

---

.github/workflows/build-on-push.yml
demo/addons/godot-openxr/CHANGES.md

The asset library bases deployment on zip files produced from a github repository which start with a folder name based on the repos name. 
This causes the `addons` folder in the zipfile to be ignored, we need to add a parent folder

Fix folder structure of godot_openxr.zip created by Github actions

---

.github/workflows/scripts/clang_format.sh
.github/workflows/scripts/file_format.sh

Ignore formatting issues in our android files, these are all support files we don't have formatting rules for (yet)

Ignore Android folder in formatting checks

---

src/openxr/OpenXRApi.cpp
src/openxr/OpenXRApi.h
src/openxr/actions/action.cpp
src/openxr/actions/action.h
src/openxr/actions/actionset.cpp
src/openxr/actions/actionset.h

There are two issues we're trying to fix here.
The first is that controllers weren't being tracking. This was due to us initialising certain things too early in the process. Interestingly enough I think this is also the likely cause that controller tracking on the index didn't always work. 
I just need to round off the solution as loosing the session requires us to clean up the spaces related to poses so we can create new ones later on.
The second problem is that hand tracking (finger tracking) currently crashes when used. It's still disabled on Quest. Still looking into this one.

Fixing controller tracking on Quest

---

demo/addons/godot-openxr/CHANGES.md
src/openxr/OpenXRApi.cpp
src/openxr/OpenXRApi.h
src/openxr/OpenXRHand.cpp
src/openxr/OpenXRPose.cpp
src/openxr/OpenXRSkeleton.cpp

OpenXR may give a zero length quaternion at initialization causing a
transform with inf values, resulting in a slew of assertion errors from
VisualServer.instance_set_transform if a VisualInstance happens to be
a child of OpenXRPose or OpenXRSkeleton.
This is a more rigorous fix than the one I first proposed: https://github.com/GodotVR/godot_openxr/pull/79

Validate space locations in OpenXRSkeleton and OpenXRPose.

---

src/gdclasses/OpenXRConfig.cpp
src/gdclasses/OpenXRConfig.h
src/gdclasses/OpenXRHand.cpp
src/gdclasses/OpenXRHand.h
src/gdclasses/OpenXRPose.cpp
src/gdclasses/OpenXRPose.h
src/gdclasses/OpenXRSkeleton.cpp
src/gdclasses/OpenXRSkeleton.h
src/gdclasses/XRInterfaceOpenXR.cpp
src/gdclasses/XRInterfaceOpenXR.h
src/godot_openxr.cpp

This is just some cleanup, I've moved the classes that are exposed to Godot into their own subfolder. 
The source code that remains in the `openxr` folder is now purely our implementation of the OpenXR system.
I think there is an argument to be made to rename the `OpenXRAPI` class to something else because it looks too similar to the naming we've applied to the exposed classes.
Finally I've added a placeholder set of files for `XRInterfaceOpenXR` which will replace `ARVRInterface` in Godot 4. I've left the `ARVRInterface` implementation in the root of the source folder because at this time this is not strictly speaking a class and it will be completely rewritten for Godot 4 anyway.

Move GDNative classes into their own subfolder

---

demo/Main.gd
src/ARVRInterface.cpp
src/gdclasses/OpenXRConfig.cpp
src/gdclasses/OpenXRConfig.h
src/openxr/OpenXRApi.cpp
src/openxr/OpenXRApi.h

This changes the logic that checks and enabled extensions in our plugin.
It works with a `map` to which we add the extensions we want.
The entry then points to a boolean that the logic either sets or clears depending on whether the extension is available.
If this pointer is a `nullptr` we deem the extension as a requirement and it not being available will fail initialization of the plugin.
Finally we enabled all extensions that were requested and found.
The boolean flags allow further logic to actually implement the usage of the extension.
I've also moved most of the FB extensions out of the Android only sphere, I suspect a number of these will become extensions also implemented by other vendors as has happened with a number of Microsoft and Valve extensions that still bear their names …

Improved extension checking logic

---

demo/Main.gd
demo/Main.tscn
demo/addons/godot-openxr/scenes/first_person_controller_vr.gd
src/gdclasses/OpenXRConfig.cpp
src/gdclasses/OpenXRConfig.h
src/openxr/OpenXRApi.cpp
src/openxr/OpenXRApi.h
src/openxr/extensions/xr_ext_hand_tracking_extension.cpp
src/openxr/extensions/xr_ext_hand_tracking_extension.h
src/openxr/extensions/xr_fb_display_refresh_rate_extension.cpp
src/openxr/extensions/xr_fb_display_refresh_rate_extension.h
src/openxr/openxr_inc.h

This PR implements an API to getting/setting refresh rates on the HMD.
These functions currently only work on the Oculus runtime, only FB has implemented an extension for this, hopefully other vendors will follow suit and add this to their OpenXR implementation as well either through the same extension or a core extension. It's important that we assume this will happen some day and expose an API to the end user that is vendor agnostic.
The new feature exposes a number of functions and properties through OpenXRConfig (note that in Godot 4 I intend to move them into the XRInterfaceOpenXR class and use proper groups).
The functions added are:
`get_refresh_rate` : Returns the current refresh rate for the HMD (return 0 if none provided or not supported)
`set_refresh_rate` : Will attempt to …

Implement refresh rate API

---

demo/ControllerInfo.gd
demo/ControllerInfo.tscn
demo/Main.tscn
demo/addons/godot-openxr/CHANGES.md
src/openxr/OpenXRApi.cpp
src/openxr/OpenXRApi.h

The current input map in the plugin had a few shortcomings.
**Vive Wand Controller**
First of all, we missed the Vive Wand interaction profile, this has now been added.
**Secondary thumbstick/trackpad**
We only had an input for our joystick that mapped to Axis 0 (x) and 1 (y), none of our other plugins ever supported more. 
Vive Wands only have a trackpad, WMR controllers and index controllers have both a joystick and trackpad.
At face value the obvious choice would be to add a trackpad input however this creates a dilemma for many games. Almost all games I've played, if not all games, don't care whether you use a joystick or trackpad, they care that you have a x,y input with which to drive functionality such as movement while often the secondary input remains unused as the two most …

Improvements to input map

---

android/build.gradle
android/src/main/assets/.gitignore
android/src/main/java/org/godotengine/plugin/vr/openxr/OpenXRPlugin.kt

This ensures that *gdns paths are still valid for projects only using the aar binary.

Copy the `addons/godot-openxr/config/` directory into the `assets` folder when building the aar binary

---

src/openxr/OpenXRApi.cpp

Added an include for algorithm, MSVC doesn't recognize `std::min` if we don't include it.

Include algorithm

---

SConstruct
openxr_loader/.gitignore

Our ignore files resulted in the pdb files from the OpenXR loader to go missing.
Adding these back in allows us a bit more debugging freedom.
Also changed scons to copy the file in place for debug builds.

Add openxr pdb files back in for debugging

---

demo/addons/godot-openxr/scenes/left_hand_nodes.tscn
demo/addons/godot-openxr/scenes/right_hand_nodes.tscn

When the gdns files were moved to config, we missed editing these two helper scenes.

Fix broken link to the hand gdns file

---

demo/Main.tscn
demo/project.godot

Moved environment into a world environment node in the demo.
Godot is getting a little silly when it comes to the default environment often loosing it resulting in a default gray background. 
For consistency moving it into a world environment node so it works all the time.

Move default env into world environment

---

demo/Main.gd
demo/Main.tscn
demo/addons/godot-openxr/CHANGES.md
demo/addons/godot-openxr/scenes/first_person_controller_vr.gd

When this plugin was originally implemented it would often be used alongside of other plugins, for instance using OpenXR for desktop and VrApi for Quest support.
As such the initialisation didn't happen automatically when you added the premade scene to your project. The idea here was that you would only call the initialisation function if you ended up using OpenXR but this does mean things do not work "out of the box".
As OpenXR is now at a stage where it can be used to deploy to all platforms it makes sense to automatically initialise it. To not remove existing logic I've added an export variable you can set in the UI which is set by default. There is an argument to do away with this completely and just initialise on `_ready`, worth a discussion here.
I've also added signals to …

Updating initialisation process

---

CONTRIBUTORS.md
demo/addons/godot-openxr/CHANGES.md
src/openxr/OpenXRApi.cpp

Tested only with the Valve Index controllers on windows. Before the change, I only got a barely perceptible vibration, even when `rumble` was set to 1.
After the change, the `rumble` value has a proper effect again for me.

haptic pulse duration was given in microseconds, rather than ms

---

src/openxr/extensions/xr_ext_hand_tracking_extension_wrapper.cpp
src/openxr/extensions/xr_ext_hand_tracking_extension_wrapper.h

Hand tracking is created on and bound to a session, so cleaning up on instance results in a crash. It should be cleaned up in `on_session_destroyed`

Hand tracking needs to be cleaned up on session destroy

---

demo/addons/godot-openxr/CHANGES.md
src/openxr/OpenXRApi.cpp

This PR adds a new interaction profile for the HP Reverb G2 controllers.

Add interaction profile for the HP Reverb G2 controllers

---

demo/ControllerInfo.gd
demo/ControllerInfo.tscn
demo/Main.tscn
demo/addons/godot-openxr/CHANGES.md
src/gdclasses/OpenXRConfig.cpp
src/gdclasses/OpenXRConfig.h
src/gdclasses/OpenXRHand.cpp
src/gdclasses/OpenXRPose.cpp
src/gdclasses/OpenXRPose.h
src/gdclasses/OpenXRSkeleton.cpp
src/openxr/OpenXRApi.cpp
src/openxr/OpenXRApi.h
src/openxr/actions/action.cpp
src/openxr/actions/action.h

This PR improves the way we're parsing our location information and uses the `locationFlags` returned to determine how accurate our tracking is.
If `locationFlags` is 0 our confidence will be set to `TRACKING_CONFIDENCE_NONE (0)`.
If our valid bits are set but our tracking bits are not, confidence will be set to `TRACKING_CONFIDENCE_LOW (1)`
If both our set our confidence will be set to `TRACKING_CONFIDENCE_HIGH (2)`
These bits are tracked for both rotation and orientation, if both are valid the both need to be tracked for the confidence to be considered high.
You have access to the confidence directly on the `OpenXRPose` node, for ARVRController nodes we do not expose this so I've added a convenience method to `OpenXRConfig` called `get_tracking_confidence`. It takes the controller id as …

Add API for accessing tracking confidence

---

demo/Main.tscn
demo/addons/godot-openxr/CHANGES.md
src/openxr/OpenXRApi.cpp
src/openxr/OpenXRApi.h
src/openxr/actions/action.cpp
src/openxr/extensions/xr_ext_hand_tracking_extension_wrapper.cpp

In Godot we update tracking data right before rendering but only the camera position and orientation is immediately used during rendering. It isn't until processing the next frame that all the nodes in Godot get position.
This has the result that any objects that are children of the camera will seem to move as you move your head instead of locked in place, and this has the result that hands seem to lag behind ever so slightly.
OpenXR however is always predicting where elements will be at time of rendering. We have control over this timing and can advance it by one frame when requesting locations.
This PR does so for obtaining the head center (which is requested when we position the camera node), the controller positions and for hand/finger tracking.
When obtaining our view transforms we …

Advance predictive timing on tracked items used *next* frame

---

demo/Main.gd
demo/Main.tscn
demo/addons/godot-openxr/CHANGES.md
demo/addons/godot-openxr/scenes/first_person_controller_vr.tscn

Complete nitpicking but this has bothered me for a long time. When I created the demo project and the First Person Controller scene I accidentally named the node `FPSController` (i.e. First Person Shooter Controller).
This PR renames it to `FPController`.
Due to the nature of how Godot works this should be a drop in fix for anyone already using this scene. It will be called `FPController` internally but still called `FPSController` in their scenes.

Renaming FPSController to FPController

---

demo/addons/godot-openxr/CHANGES.md
src/openxr/OpenXRApi.cpp
src/openxr/actions/action.cpp

Fixes #157, as Malcolm correctly found out, when we specify the `p_can_be_negative` parameter as false a range from 0.0 to 1.0 is rescaled to -1.0 to 1.0. 
I have no memory of when and why we did this, it must have been a choice that made sense 4 years ago when this was all first implemented but it gives unexpected behavior.
This PR changes that property to true in the two instances it was false, namely trigger and grip input, making sure the value we pass stays exactly what it is and the expected behavior of this value being between 0.0 and 1.0 is respected.
This is by definition a breaking change but I think most people will have build their logic expecting this value being between 0.0 and 1.0 as is consistent with other plugins. Therefor I feel it is safe to add this in the 1.2 …

Fix controller float input

---

demo/ControllerInfo.gd
demo/Main.gd
demo/Main.tscn
demo/Screen.gd
demo/Screen.tscn
demo/addons/godot-openxr/CHANGES.md
demo/addons/godot-openxr/scenes/first_person_controller_vr.gd
demo/addons/godot-openxr/scenes/visualise_bounds.gd
src/gdclasses/OpenXRPose.cpp
src/openxr/OpenXRApi.cpp
src/openxr/OpenXRApi.h
src/openxr/actions/actionset.cpp
src/openxr/include/util.h

We've been having some weird issues with handling colors in the plugin.
The OpenXR specification is clear, if you use an sRGB texture type it is expecting the rendering to be done in sRGB with the hardware converting to linear where needed, if you use any other texture type the rendering is supposed to be done/remain in linear color space.
Godot renders in linear color space with its GLES3 driver, then color corrects and converts the result to sRGB when copying that into the buffers setup by OpenXR. That works fine.
Godot renders in sRGB color space with its GLES2 driver and when no post effects are used this is rendered directly into the buffers setup by OpenXR.
The problem we encounter is that under a true OpenGLES2 context, sRGB is not supported. On desktop we're actually running …

Improve logic for selecting swapchain format to use

---

demo/addons/godot-openxr/CHANGES.md
src/openxr/OpenXRApi.cpp

I went through the OpenXR spec to add a number of missing entries to our interaction profiles which are handled by extensions.
As these are extensions, not supported by the core, these will give an entry in the log on platforms that don't support or know about these profiles. I'm specifically checking for `XR_ERROR_PATH_UNSUPPORTED` so that it is just normal output, not seen as an error. 
Anyway, the following are added:
- /interaction_profiles/samsung/odyssey_controller , I think only supported on the WMR runtime
- /interaction_profiles/htc/vive_cosmos_controller, this one is supported by SteamVR
- /interaction_profiles/htc/vive_focus3_controller, we don't run on the Focus3 (yet) but maybe some day
- /interaction_profiles/huawei/controller, we don't run on these yet but they should be …

Add interaction profiles related to extensions

---

src/openxr/OpenXRApi.cpp

This works around issue #173. It may be that clearing frame state before xrWaitTime is enough, but in case we still get weird numbers, I'm checking for any display period more then 0.5 seconds and clearing it if we receive that. The value retrieved amounted to something like 16570 hours :)
Seeing this is Quest over airlink the best guess I have is that there is some sort of hickup and we're not getting correct data.

Reset frame state before xrWaitTime and validate display period

---

src/openxr/OpenXRApi.cpp

The [XrSwapchain](https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrSwapchain) handle must be eventually freed via the [xrDestroySwapchain](https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#xrDestroySwapchain) function.

Clean up swapchains properly with xrDestroySwapchain

---

demo/Main.gd
demo/Main.tscn
demo/addons/godot-openxr/scenes/first_person_controller_vr.gd
demo/scenes/Screen.gd
demo/scenes/Screen.tscn

Right now the properly on the first person controller script just auto starts passthrough.
This change makes it a proper toggle with which to turn on/off passthrough.
@m4gr3d is this the correct way to implement this?

Make passthrough a toggle on first person controller

---

src/gdclasses/OpenXRConfig.cpp
src/gdclasses/OpenXRConfig.h
src/openxr/OpenXRApi.cpp
src/openxr/OpenXRApi.h

Adds an option to our configuration object to set the play space type between view, local and stage.
See https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#reference-spaces for more information

Add configuration setting for play space type

---

src/openxr/OpenXRApi.cpp
src/openxr/OpenXRApi.h

Looking into the issue of the swapchain not releasing properly and locking up the left eye buffer when turning on screen recording on the Quest (2). 
Still investigating this but the change so far ensures we end the frame properly even if there was an issue.
Note that we're also including #207 in this just in case this was an issue with an older version of the SDK. 
Waiting on feedback on the Oculus forum to see if anyone else has encountered this:
https://forums.oculusvr.com/t5/OpenXR-Development/Eye-freezes-when-screen-recording/td-p/963673

Fix swapchain release issue

---

src/openxr/OpenXRApi.cpp

This is potentially a breaking change for people who are using world scale. As this was brought to my attention because it was causing issues for people doing so I think this is a safe revert.
I introduced scaling of the basis in commit 0d2ea910fdb761ea9c28eb51e78e6e6ebc0fa210, which is not what we should do here. 
When using world scale it is nice to apply the scaling to ensure controller meshes are scaled, but this should be applied on the controller mesh, NOT on the ARVRController node. Scaling the controller node has a lot of unwanted side effects as it adversely effects physics and as we may child a lot of things that are not expecting to be scaled (such as our teleport visualization).

Do not scale basis of transform with world scale!

---

demo/addons/godot-openxr/CHANGES.md
src/openxr/OpenXRApi.cpp
src/openxr/OpenXRApi.h

Just isolating the workaround by @mgschwan in #214 for re-initialising the swapchain when it fails to release.
This is a weird issue on Oculus Quest where when screen recording starts, we can no longer release images in the swapchain without a good explanation as to what we're doing incorrectly. 
Once we figure out the proper fix we can revert this PR.

Mgschwans workaround for failed release of swapchain

---

demo/addons/godot-openxr/CHANGES.md
demo/addons/godot-openxr/scenes/first_person_controller_vr.gd
src/openxr/OpenXRApi.cpp
src/openxr/include/signals_util.h

Added missing signals on session state changes. This is a continuation of this work in PR #214. I did not add ready as we already have `openxr_session_begun` being triggered on our ready state change and it is thus the same thing.

Adding idle, synchronized, loss pending and exiting signals

---

demo/addons/godot-openxr/CHANGES.md
src/gdclasses/OpenXRConfig.cpp
src/gdclasses/OpenXRConfig.h

When exposing properties to Godot using enums, they must be sequential. Some of the enums in OpenXR aren't and we can't use them as such.
GDNative does not allow us to expose enums properly so they can be used in code (GDExtension in Godot 4 can), I have still added enum definitions where this is applicable for clarity and to ensure that our mapping code is more readable and less prone to mistakes.
Fixes #212
Replaces #216

Add enums for clarity and fix incorrect play space type
